// SEARCH USER
export const SUBMIT_SEARCH_USER = "SUBMIT_SEARCH_USER";
export const START_SEARCH_USER = "START_SEARCH_USER";
export const COMPLETE_SEARCH_USER = "COMPLETE_SEARCH_USER";
export const FAIL_SEARCH_USER = "FAIL_SEARCH_USER";